name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - run: pytest

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image
      run: docker build -t my-flask-app .

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to AQUINOVM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/azureuser/SoftEng
          git pull origin main
          docker build -t my-flask-app .
          docker stop flask_app || true
          docker rm flask_app || true
          docker run -d -p 80:5000 --name flask_app my-flask-app